#!/usr/bin/env python3
"""Extracts the CELT tables needed by opuspp from the libopus 1.6.1 sources.

The C sources are run through the preprocessor (float build, no custom modes,
no QEXT) so every #ifdef is resolved exactly like in the reference build, then
the initialisers of the requested arrays are copied verbatim into
include/opuspp/detail/celt_tables.hpp.

Usage: tools/gen_tables.py [path-to-opus-1.6.1]   (default: ../opus-1.6.1 next
to the project)
"""
import re
import subprocess
import sys
from pathlib import Path

project = Path(__file__).resolve().parent.parent
root = Path(sys.argv[1]) if len(sys.argv) > 1 else project.parent / "opus-1.6.1"
out = project / "include/opuspp/detail/celt_tables.hpp"

CFLAGS = ["-E", "-P", "-DOPUS_BUILD", "-DVAR_ARRAYS", "-I" + str(root / "include"),
          "-I" + str(root / "celt"), "-I" + str(root)]


def preprocess(src):
    return subprocess.run(["gcc", *CFLAGS, str(root / src)], check=True,
                          capture_output=True, text=True).stdout


# (source, C name, C++ type, C++ name)
TABLES = [
    ("celt/modes.c", "eband5ms", "std::int16_t", "eband5ms"),
    ("celt/modes.c", "band_allocation", "std::uint8_t", "band_allocation"),
    ("celt/modes.c", "window120", "float", "window120"),
    ("celt/modes.c", "logN400", "std::int16_t", "logN400"),
    ("celt/modes.c", "cache_index50", "std::int16_t", "cache_index50"),
    ("celt/modes.c", "cache_bits50", "std::uint8_t", "cache_bits50"),
    ("celt/modes.c", "cache_caps50", "std::uint8_t", "cache_caps50"),
    ("celt/modes.c", "fft_twiddles48000_960", "Complex", "fft_twiddles"),
    ("celt/modes.c", "fft_bitrev240", "std::int16_t", "fft_bitrev240"),
    ("celt/modes.c", "fft_bitrev60", "std::int16_t", "fft_bitrev60"),
    ("celt/modes.c", "mdct_twiddles960", "float", "mdct_twiddles960"),
    ("celt/cwrs.c", "CELT_PVQ_U_DATA", "std::uint32_t", "pvq_u_data"),
    ("celt/rate.c", "LOG2_FRAC_TABLE", "std::uint8_t", "log2_frac_table"),
    ("celt/quant_bands.c", "e_prob_model", "std::uint8_t", "e_prob_model"),
    ("celt/quant_bands.c", "eMeans", "float", "e_means"),
]


def extract(text, name):
    m = re.search(r"\b" + re.escape(name) + r"\s*((?:\[[^\]]*\])+)\s*=\s*", text)
    if not m:
        raise SystemExit(f"table {name} not found")
    dims = m.group(1)
    i = m.end()
    assert text[i] == "{"
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return dims, text[i:j + 1]
    raise SystemExit(f"unterminated initialiser for {name}")


def clean(init):
    init = re.sub(r"/\*.*?\*/", "", init, flags=re.S)
    init = re.sub(r"\(opus_int16\)|\(opus_int32\)|\(opus_val16\)|\(celt_coef\)", "", init)
    lines = [ln.strip() for ln in init.splitlines()]
    return "\n".join("   " + ln if ln not in ("{", "}") else ln for ln in lines if ln)


cache = {}
body = []
for src, cname, ctype, name in TABLES:
    if src not in cache:
        cache[src] = preprocess(src)
    dims, init = extract(cache[src], cname)
    dims = re.sub(r"\s+", "", dims)
    body.append(f"alignas(64) inline constexpr {ctype} {name}{dims} = {clean(init)};\n")

header = f"""// Generated by tools/gen_tables.py from libopus 1.6.1 -- do not edit.
// Copyright (c) 2007-2008 CSIRO, 2007-2011 Xiph.Org Foundation, 2010-2011 Skype Limited.
// SPDX-License-Identifier: BSD-3-Clause
#pragma once

#include <cstdint>

namespace opuspp::detail::tables {{

struct Complex {{
   float r;
   float i;
}};

{chr(10).join(body)}
}} // namespace opuspp::detail::tables
"""
out.write_text(header)
print(f"wrote {out}")
